import { ThemeProvider } from "@/components/theme.provider";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const mainFont = Space_Grotesk({
  weight: ["400", "500", "600", "700"],
  preload: true,
  adjustFontFallback: true,
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface I_Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: I_Props) {
  return (
    <html lang="en" className={mainFont.className} suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="light">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
